# Form implementation generated from reading ui file 'Window_2_Input.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Window_2_Input(object):
    def setupUi(self, Window_2_Input):
        Window_2_Input.setObjectName("Window_2_Input")
        Window_2_Input.resize(1000, 800)
        Window_2_Input.setStyleSheet("background-color: rgb(220, 138, 221);")
        self.centralwidget = QtWidgets.QWidget(parent=Window_2_Input)
        self.centralwidget.setObjectName("centralwidget")
        self.firstThingsFirst_title_text = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.firstThingsFirst_title_text.setGeometry(QtCore.QRect(0, 20, 1001, 51))
        self.firstThingsFirst_title_text.setAutoFillBackground(True)
        self.firstThingsFirst_title_text.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.firstThingsFirst_title_text.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.firstThingsFirst_title_text.setLineWidth(0)
        self.firstThingsFirst_title_text.setObjectName("firstThingsFirst_title_text")
        self.cv_browseFile_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.cv_browseFile_button.setGeometry(QtCore.QRect(420, 120, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.cv_browseFile_button.setFont(font)
        self.cv_browseFile_button.setObjectName("cv_browseFile_button")
        self.button_next_page3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_next_page3.setGeometry(QtCore.QRect(680, 500, 200, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.button_next_page3.setFont(font)
        self.button_next_page3.setObjectName("button_next_page3")
        self.button_back_page1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_back_page1.setGeometry(QtCore.QRect(130, 510, 200, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.button_back_page1.setFont(font)
        self.button_back_page1.setObjectName("button_back_page1")
        self.button_availibility_date = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.button_availibility_date.setGeometry(QtCore.QRect(520, 180, 121, 26))
        self.button_availibility_date.setObjectName("button_availibility_date")
        self.radioButton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(400, 210, 112, 23))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(520, 210, 112, 23))
        self.radioButton_2.setObjectName("radioButton_2")
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(340, 260, 341, 31))
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.slider_wordsAmount = QtWidgets.QSlider(parent=self.centralwidget)
        self.slider_wordsAmount.setGeometry(QtCore.QRect(430, 340, 160, 16))
        self.slider_wordsAmount.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider_wordsAmount.setObjectName("slider_wordsAmount")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(400, 340, 31, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(600, 340, 31, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(350, 400, 81, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(600, 400, 71, 17))
        self.label_4.setObjectName("label_4")
        self.slider_wordsAmount_2 = QtWidgets.QSlider(parent=self.centralwidget)
        self.slider_wordsAmount_2.setGeometry(QtCore.QRect(430, 400, 160, 20))
        self.slider_wordsAmount_2.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider_wordsAmount_2.setObjectName("slider_wordsAmount_2")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(480, 320, 61, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(460, 380, 101, 20))
        self.label_6.setObjectName("label_6")
        self.label_availabilty = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_availabilty.setGeometry(QtCore.QRect(400, 180, 111, 20))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_availabilty.setFont(font)
        self.label_availabilty.setObjectName("label_availabilty")
        Window_2_Input.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Window_2_Input)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menubar.setObjectName("menubar")
        Window_2_Input.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Window_2_Input)
        self.statusbar.setObjectName("statusbar")
        Window_2_Input.setStatusBar(self.statusbar)

        self.retranslateUi(Window_2_Input)
        QtCore.QMetaObject.connectSlotsByName(Window_2_Input)

    def retranslateUi(self, Window_2_Input):
        _translate = QtCore.QCoreApplication.translate
        Window_2_Input.setWindowTitle(_translate("Window_2_Input", "LazyApp"))
        self.firstThingsFirst_title_text.setHtml(_translate("Window_2_Input", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:26pt; font-weight:700;\">First things first!</span></p></body></html>"))
        self.cv_browseFile_button.setText(_translate("Window_2_Input", "CV"))
        self.button_next_page3.setText(_translate("Window_2_Input", "NEXT"))
        self.button_back_page1.setText(_translate("Window_2_Input", "BACK"))
        self.radioButton.setText(_translate("Window_2_Input", "FULL-TIME"))
        self.radioButton_2.setText(_translate("Window_2_Input", "PART-TIME"))
        self.textEdit.setHtml(_translate("Window_2_Input", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#dc8add;\">ANNUAL SALARY</span></p></body></html>"))
        self.label.setText(_translate("Window_2_Input", "250"))
        self.label_2.setText(_translate("Window_2_Input", "400"))
        self.label_3.setText(_translate("Window_2_Input", "RATIONAL"))
        self.label_4.setText(_translate("Window_2_Input", "CREATIVE"))
        self.label_5.setText(_translate("Window_2_Input", "WORDS"))
        self.label_6.setText(_translate("Window_2_Input", "AI BEHAVIOUR"))
        self.label_availabilty.setText(_translate("Window_2_Input", "AVAILABILITY"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Window_2_Input = QtWidgets.QMainWindow()
    ui = Ui_Window_2_Input()
    ui.setupUi(Window_2_Input)
    Window_2_Input.show()
    sys.exit(app.exec())
