# Form implementation generated from reading ui file 'waiting.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Waiting(object):
    def setupUi(self, Waiting):
        Waiting.setObjectName("Waiting")
        Waiting.resize(450, 440)
        self.label = QtWidgets.QLabel(parent=Waiting)
        self.label.setGeometry(QtCore.QRect(0, 0, 450, 440))
        self.label.setMinimumSize(QtCore.QSize(450, 440))
        self.label.setMaximumSize(QtCore.QSize(450, 440))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("patience.webp"))
        self.label.setObjectName("label")
        self.label.setAutoFillBackground(False)

        self.retranslateUi(Waiting)
        QtCore.QMetaObject.connectSlotsByName(Waiting)

    def retranslateUi(self, Waiting):
        _translate = QtCore.QCoreApplication.translate
        Waiting.setWindowTitle(_translate("Waiting", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Waiting = QtWidgets.QWidget()
    ui = Ui_Waiting()
    ui.setupUi(Waiting)
    Waiting.show()
    sys.exit(app.exec())
